"""
winrt first test
"""

import winrt.windows.ui.notifications as notifications
import winrt.windows.data.xml.dom as dom

tString = """
<toast>
    <visual>
        <binding template='ToastGeneric'>
            <text>Sample toast</text>
            <text>Yo time to close your eyes</text>
        </binding>
    </visual>
</toast>
"""

xDoc = dom.XmlDocument()
xDoc.load_xml(tString)

app = r"Microsoft.AutoGenerated.{29002F08-8FC3-0BEC-73FD-C3026E3BF285}"
notifications.ToastNotificationManager.create_toast_notifier(app).show(notifications.ToastNotification(xDoc))

